FROM alpine:3.7
MAINTAINER jiezi <shuoshadow@foxmail.com>

RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
RUN mkdir -p /opt/dterm
COPY dterm /opt/dterm/
COPY statics /opt/dterm/statics

WORKDIR /opt/dterm

ENTRYPOINT ["./dterm"]